# Generated by Django 4.1.3 on 2022-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0002_cession_credits_data_from_rosp_execut_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection_debt',
            options={'verbose_name': 'Взыскание долга', 'verbose_name_plural': 'Взыскание долга'},
        ),
        migrations.AlterModelOptions(
            name='data_from_rosp_execut_product',
            options={'verbose_name': 'Данные из РОСП об ИП', 'verbose_name_plural': 'Данные из РОСП об ИП'},
        ),
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name': 'Судебный раздел', 'verbose_name_plural': 'Судебный раздел'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Библиотека', 'verbose_name_plural': 'Библиотека'},
        ),
        migrations.AlterModelOptions(
            name='mail_in',
            options={'verbose_name': 'Входящая корреспонденция', 'verbose_name_plural': 'Входящая корреспонденция'},
        ),
        migrations.AlterModelOptions(
            name='mail_out',
            options={'verbose_name': 'Исходящая корреспонденция', 'verbose_name_plural': 'Исходящая корреспонденция'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='pyments',
            options={'verbose_name': 'Платежи', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='transaction_exchange',
            options={'verbose_name': 'Регистрация изменения данных', 'verbose_name_plural': 'Регистрация изменения данных'},
        ),
        migrations.RemoveField(
            model_name='debtors',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='debtors',
            name='name_2',
        ),
        migrations.AddField(
            model_name='debtors',
            name='first_name_1',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя должника (по договору)'),
        ),
        migrations.AddField(
            model_name='debtors',
            name='first_name_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя должника (изменения)'),
        ),
        migrations.AddField(
            model_name='debtors',
            name='last_name_1',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия должника (по договору)'),
        ),
        migrations.AddField(
            model_name='debtors',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия должника (изменения)'),
        ),
        migrations.AddField(
            model_name='debtors',
            name='second_name_1',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество должника (по договору)'),
        ),
        migrations.AddField(
            model_name='debtors',
            name='second_name_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество должника (изменения)'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='address_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='address_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='index_add_1',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Индекс прописки'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='index_add_2',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Индекс проживания'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='passport_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='snils',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='СНИЛС'),
        ),
    ]
