# Generated by Django 4.1.3 on 2022-12-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0003_alter_collection_debt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='executive_document',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='debtors.executive_documents', verbose_name='Исполнительный документ'),
        ),
        migrations.AddConstraint(
            model_name='cession',
            constraint=models.UniqueConstraint(fields=('name', 'number'), name='unique_cession'),
        ),
        migrations.AddConstraint(
            model_name='credits',
            constraint=models.UniqueConstraint(fields=('creditor', 'number'), name='unique_credits'),
        ),
        migrations.AddConstraint(
            model_name='debtors',
            constraint=models.UniqueConstraint(fields=('last_name_1', 'first_name_1', 'second_name_1', 'birthday'), name='unique_debtors'),
        ),
        migrations.AddConstraint(
            model_name='departments',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_departments'),
        ),
        migrations.AddConstraint(
            model_name='executive_documents',
            constraint=models.UniqueConstraint(fields=('number', 'date', 'case_number'), name='unique_ed'),
        ),
        migrations.AddConstraint(
            model_name='executive_productions',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_ep'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_library'),
        ),
        migrations.AddConstraint(
            model_name='mail_in',
            constraint=models.UniqueConstraint(fields=('sequence_num',), name='unique_mail_in'),
        ),
        migrations.AddConstraint(
            model_name='mail_out',
            constraint=models.UniqueConstraint(fields=('sequence_num',), name='unique_mail_out'),
        ),
        migrations.AddConstraint(
            model_name='positions',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_positions'),
        ),
    ]
