# Generated by Django 4.1.3 on 2022-12-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0004_alter_legal_executive_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cession',
            name='date_old_cession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Даты предыдущих цессий'),
        ),
    ]
