# Generated by Django 4.1.3 on 2022-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0005_alter_cession_date_old_cession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='date_ent',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='executive_productions',
            name='address_rosp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес РОСП'),
        ),
        migrations.AddField(
            model_name='executive_productions',
            name='pristav',
            field=models.CharField(blank=True, max_length=50, verbose_name='Пристав'),
        ),
        migrations.AddField(
            model_name='executive_productions',
            name='pristav_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон пристава'),
        ),
        migrations.AddField(
            model_name='executive_productions',
            name='rosp',
            field=models.CharField(blank=True, max_length=50, verbose_name='РОСП'),
        ),
        migrations.AlterField(
            model_name='cession',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата цессии'),
        ),
        migrations.AlterField(
            model_name='collection_debt',
            name='date_presentation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата предъявления ИД'),
        ),
        migrations.AlterField(
            model_name='collection_debt',
            name='date_return',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата ИД'),
        ),
        migrations.AlterField(
            model_name='data_from_rosp_execut_product',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания ИП'),
        ),
        migrations.AlterField(
            model_name='data_from_rosp_execut_product',
            name='date_on',
            field=models.DateField(verbose_name='Дата возбуждения ИП'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='executive_documents',
            name='date_of_receipt_ed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ИД'),
        ),
        migrations.AlterField(
            model_name='executive_productions',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания ИП'),
        ),
        migrations.AlterField(
            model_name='executive_productions',
            name='date_on',
            field=models.DateField(blank=True, verbose_name='Дата возбуждения ИП'),
        ),
        migrations.AlterField(
            model_name='executive_productions',
            name='date_request',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения данных из РОСП'),
        ),
        migrations.AlterField(
            model_name='library',
            name='list',
            field=models.JSONField(verbose_name='Список'),
        ),
        migrations.AlterField(
            model_name='pyments',
            name='summa',
            field=models.FloatField(verbose_name='Сумма платежа'),
        ),
    ]
