# Generated by Django 4.1.3 on 2023-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0006_rename_date_ent_credits_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imported_Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование импортируемого реестра')),
                ('date', models.DateField(null=True, verbose_name='Дата импорта')),
                ('registry', models.JSONField(verbose_name='Реестр')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Импортируемый реестр',
                'verbose_name_plural': 'Импортируемые реестры',
            },
        ),
        migrations.CreateModel(
            name='Registry_Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=50, verbose_name='Наименование поля в БД')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование столбца в таблице frontend')),
                ('turn', models.IntegerField(null=True, verbose_name='Номер очередности')),
                ('redactor', models.CharField(default='1', max_length=20, verbose_name='Кто может редактировать')),
            ],
            options={
                'verbose_name': 'Наименование столбцов реестра',
                'verbose_name_plural': 'Наименование столбцов реестра',
            },
        ),
        migrations.AddConstraint(
            model_name='registry_headers',
            constraint=models.UniqueConstraint(fields=('name_field', 'name', 'turn'), name='unique_registry_headers'),
        ),
        migrations.AddConstraint(
            model_name='imported_registry',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_imported_registry'),
        ),
    ]
