# Generated by Django 4.0.5 on 2023-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0008_alter_profile_department_alter_profile_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry_headers',
            options={'verbose_name': 'Заголовок столбцов реестра', 'verbose_name_plural': 'Заголовки столбцов реестра'},
        ),
        migrations.RemoveConstraint(
            model_name='registry_headers',
            name='unique_registry_headers',
        ),
        migrations.RemoveField(
            model_name='registry_headers',
            name='name',
        ),
        migrations.AddField(
            model_name='registry_headers',
            name='headers',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок столбца в таблице frontend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry_headers',
            name='headers_key',
            field=models.CharField(default=1, max_length=100, verbose_name='Ключ заголовка столбца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry_headers',
            name='model',
            field=models.CharField(default=1, max_length=50, verbose_name='Наименование модели БД'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registry_headers',
            name='name_field',
            field=models.CharField(max_length=50, verbose_name='Наименование поля в Модели'),
        ),
        migrations.AddConstraint(
            model_name='registry_headers',
            constraint=models.UniqueConstraint(fields=('headers', 'headers_key', 'turn'), name='unique_registry_headers'),
        ),
    ]
