# Generated by Django 4.0.5 on 2023-01-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0009_alter_registry_headers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry_headers',
            name='width_field',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина столбца'),
        ),
    ]
